dev:
  mysql:
    willshark:
      host: 172.16.27.96
      port: 3306
      user: will
      password: 'admin@123'
      dataBase: vrpm
      parseTime: True
      maxIdleConns: 10
      maxOpenConns: 30
      connMaxLifetime: 28800
      connMaxIdletime: 7200
  redis:
    willshark:
      host: 172.16.27.46:9736
      password: "hasKITs!"
      database: 0
      maxIdleNum: 50
      maxActive: 10000
      maxIdleTimeout: 600
      connectTimeout: 1
      readTimeout: 2
  rocketmq:
    groupName: test-rocket
    topic: test-rocket
    host:
      - 127.0.0.1:9876
    retry: 3
  jaeger:
    enable: false
    host: http://127.0.0.1:14268