dev:
  mysql:
    will:
      Host: 172.16.27.96
      Port: 3306
      User: will
      Password: 'admin@123'
      DataBase: vrpm
      ParseTime: True
      MaxIdleConns: 10
      MaxOpenConns: 30
      ConnMaxLifetime: 28800
      ConnMaxIdletime: 7200
  redis:
    will:
      host: 172.16.27.97:6379
      password: ""
      database: 0
      maxIdleNum: 50
      maxActive: 10000
      maxIdleTimeout: 600
      connectTimeout: 1
      readTimeout: 2
  rocketmq:
    GroupName: test-rocket
    Topic: test-rocket
    Host:
      - 127.0.0.1:9876
    Retry: 3